=== ThomasWagner-dev/Sudoku/sudoku.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="https://namespace.fh-muenster.de/studium"
           targetNamespace="https://namespace.fh-muenster.de/studium">
    <xs:element name="sudoku" type="sudokuType"/>

    <xs:complexType name="sudokuType">
        <xs:sequence>
            <xs:element name="feld" type="feldType" minOccurs="81" maxOccurs="81"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="feldType">
      <xs:sequence>
      <xs:element type="wert" name="wert"/>
      </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="wert">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="9"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ThomasWagner-dev/Sudoku/data/highNumber.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><sudoku xmlns="https://namespace.fh-muenster.de/studium" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://namespace.fh-muenster.de/studium ../sudoku.xsd"><feld><wert>17</wert></feld><feld><wert>3</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>1</wert></feld><feld><wert>9</wert></feld><feld><wert>5</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>8</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>6</wert></feld><feld><wert>0</wert></feld><feld><wert>8</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>6</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>4</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>8</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>1</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>2</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>6</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>2</wert></feld><feld><wert>8</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>4</wert></feld><feld><wert>1</wert></feld><feld><wert>9</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>5</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>0</wert></feld><feld><wert>7</wert></feld><feld><wert>0</wert></feld></sudoku>
